# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kuberbolt.discovery import discovery_pb2 as discovery__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in discovery_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeManagerStub:
    """──────────────────────────────────────────────────────────────────────────────
    NodeManager — discovery-layer service.

    The Python SDK ("scout") discovers peer endpoints (currently hardcoded
    dummies; Nostr relay integration comes later) and hands them to the Go
    daemon ("engine") via this RPC.
    ──────────────────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandoverPeers = channel.unary_unary(
                '/kuberbolt.discovery.v1.NodeManager/HandoverPeers',
                request_serializer=discovery__pb2.PeerHandoverRequest.SerializeToString,
                response_deserializer=discovery__pb2.PeerHandoverResponse.FromString,
                _registered_method=True)


class NodeManagerServicer:
    """──────────────────────────────────────────────────────────────────────────────
    NodeManager — discovery-layer service.

    The Python SDK ("scout") discovers peer endpoints (currently hardcoded
    dummies; Nostr relay integration comes later) and hands them to the Go
    daemon ("engine") via this RPC.
    ──────────────────────────────────────────────────────────────────────────────
    """

    def HandoverPeers(self, request, context):
        """HandoverPeers delivers discovered peer endpoints to the engine.
        For the bootstrap phase this is fire-and-forget: the engine logs the
        endpoints and returns an ack.  Real processing logic will be added later.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandoverPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.HandoverPeers,
                    request_deserializer=discovery__pb2.PeerHandoverRequest.FromString,
                    response_serializer=discovery__pb2.PeerHandoverResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kuberbolt.discovery.v1.NodeManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kuberbolt.discovery.v1.NodeManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeManager:
    """──────────────────────────────────────────────────────────────────────────────
    NodeManager — discovery-layer service.

    The Python SDK ("scout") discovers peer endpoints (currently hardcoded
    dummies; Nostr relay integration comes later) and hands them to the Go
    daemon ("engine") via this RPC.
    ──────────────────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def HandoverPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kuberbolt.discovery.v1.NodeManager/HandoverPeers',
            discovery__pb2.PeerHandoverRequest.SerializeToString,
            discovery__pb2.PeerHandoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
