// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FinancialPodService_CallService_FullMethodName    = "/kuberbolt.v1.FinancialPodService/CallService"
	FinancialPodService_PayHoldInvoice_FullMethodName = "/kuberbolt.v1.FinancialPodService/PayHoldInvoice"
	FinancialPodService_GetBudgetInfo_FullMethodName  = "/kuberbolt.v1.FinancialPodService/GetBudgetInfo"
)

// FinancialPodServiceClient is the client API for FinancialPodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────────────────────────────────────
// FinancialPodService — the single gRPC service exposed by the Financial Pod.
// Clients call CallService to request AI compute; the pod gates access with L402.
// ──────────────────────────────────────────────────────────────────────────────
type FinancialPodServiceClient interface {
	// CallService is the primary compute-for-payment RPC.
	// Unauthenticated requests receive a 402 challenge (invoice + macaroon).
	// Authenticated requests (macaroon + preimage) are forwarded to the AI brain.
	CallService(ctx context.Context, in *CallServiceRequest, opts ...grpc.CallOption) (*CallServiceResponse, error)
	// PayHoldInvoice triggers an outgoing payment from this node's wallet.
	PayHoldInvoice(ctx context.Context, in *PayHoldInvoiceRequest, opts ...grpc.CallOption) (*PayHoldInvoiceResponse, error)
	// GetBudgetInfo returns current daily/monthly spend counters.
	GetBudgetInfo(ctx context.Context, in *GetBudgetInfoRequest, opts ...grpc.CallOption) (*GetBudgetInfoResponse, error)
}

type financialPodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialPodServiceClient(cc grpc.ClientConnInterface) FinancialPodServiceClient {
	return &financialPodServiceClient{cc}
}

func (c *financialPodServiceClient) CallService(ctx context.Context, in *CallServiceRequest, opts ...grpc.CallOption) (*CallServiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallServiceResponse)
	err := c.cc.Invoke(ctx, FinancialPodService_CallService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPodServiceClient) PayHoldInvoice(ctx context.Context, in *PayHoldInvoiceRequest, opts ...grpc.CallOption) (*PayHoldInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PayHoldInvoiceResponse)
	err := c.cc.Invoke(ctx, FinancialPodService_PayHoldInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPodServiceClient) GetBudgetInfo(ctx context.Context, in *GetBudgetInfoRequest, opts ...grpc.CallOption) (*GetBudgetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBudgetInfoResponse)
	err := c.cc.Invoke(ctx, FinancialPodService_GetBudgetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialPodServiceServer is the server API for FinancialPodService service.
// All implementations must embed UnimplementedFinancialPodServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────────────────────────────────────
// FinancialPodService — the single gRPC service exposed by the Financial Pod.
// Clients call CallService to request AI compute; the pod gates access with L402.
// ──────────────────────────────────────────────────────────────────────────────
type FinancialPodServiceServer interface {
	// CallService is the primary compute-for-payment RPC.
	// Unauthenticated requests receive a 402 challenge (invoice + macaroon).
	// Authenticated requests (macaroon + preimage) are forwarded to the AI brain.
	CallService(context.Context, *CallServiceRequest) (*CallServiceResponse, error)
	// PayHoldInvoice triggers an outgoing payment from this node's wallet.
	PayHoldInvoice(context.Context, *PayHoldInvoiceRequest) (*PayHoldInvoiceResponse, error)
	// GetBudgetInfo returns current daily/monthly spend counters.
	GetBudgetInfo(context.Context, *GetBudgetInfoRequest) (*GetBudgetInfoResponse, error)
	mustEmbedUnimplementedFinancialPodServiceServer()
}

// UnimplementedFinancialPodServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialPodServiceServer struct{}

func (UnimplementedFinancialPodServiceServer) CallService(context.Context, *CallServiceRequest) (*CallServiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallService not implemented")
}
func (UnimplementedFinancialPodServiceServer) PayHoldInvoice(context.Context, *PayHoldInvoiceRequest) (*PayHoldInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PayHoldInvoice not implemented")
}
func (UnimplementedFinancialPodServiceServer) GetBudgetInfo(context.Context, *GetBudgetInfoRequest) (*GetBudgetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBudgetInfo not implemented")
}
func (UnimplementedFinancialPodServiceServer) mustEmbedUnimplementedFinancialPodServiceServer() {}
func (UnimplementedFinancialPodServiceServer) testEmbeddedByValue()                             {}

// UnsafeFinancialPodServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialPodServiceServer will
// result in compilation errors.
type UnsafeFinancialPodServiceServer interface {
	mustEmbedUnimplementedFinancialPodServiceServer()
}

func RegisterFinancialPodServiceServer(s grpc.ServiceRegistrar, srv FinancialPodServiceServer) {
	// If the following call panics, it indicates UnimplementedFinancialPodServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialPodService_ServiceDesc, srv)
}

func _FinancialPodService_CallService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPodServiceServer).CallService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialPodService_CallService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPodServiceServer).CallService(ctx, req.(*CallServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPodService_PayHoldInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayHoldInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPodServiceServer).PayHoldInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialPodService_PayHoldInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPodServiceServer).PayHoldInvoice(ctx, req.(*PayHoldInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPodService_GetBudgetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBudgetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPodServiceServer).GetBudgetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialPodService_GetBudgetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPodServiceServer).GetBudgetInfo(ctx, req.(*GetBudgetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialPodService_ServiceDesc is the grpc.ServiceDesc for FinancialPodService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialPodService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kuberbolt.v1.FinancialPodService",
	HandlerType: (*FinancialPodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallService",
			Handler:    _FinancialPodService_CallService_Handler,
		},
		{
			MethodName: "PayHoldInvoice",
			Handler:    _FinancialPodService_PayHoldInvoice_Handler,
		},
		{
			MethodName: "GetBudgetInfo",
			Handler:    _FinancialPodService_GetBudgetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_service.proto",
}
