// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind of service being requested (e.g. "text-completion", "image-gen").
	ServiceKind string `protobuf:"bytes,1,opt,name=service_kind,json=serviceKind,proto3" json:"service_kind,omitempty"`
	// JSON-encoded job definition. Content is service-kind-specific.
	JobSpec []byte `protobuf:"bytes,2,opt,name=job_spec,json=jobSpec,proto3" json:"job_spec,omitempty"`
	// Present only on the authenticated retry (after payment).
	MacaroonHex string `protobuf:"bytes,3,opt,name=macaroon_hex,json=macaroonHex,proto3" json:"macaroon_hex,omitempty"`
	// Present only on the authenticated retry (after payment).
	PreimageHex   string `protobuf:"bytes,4,opt,name=preimage_hex,json=preimageHex,proto3" json:"preimage_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallServiceRequest) Reset() {
	*x = CallServiceRequest{}
	mi := &file_agent_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServiceRequest) ProtoMessage() {}

func (x *CallServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServiceRequest.ProtoReflect.Descriptor instead.
func (*CallServiceRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{0}
}

func (x *CallServiceRequest) GetServiceKind() string {
	if x != nil {
		return x.ServiceKind
	}
	return ""
}

func (x *CallServiceRequest) GetJobSpec() []byte {
	if x != nil {
		return x.JobSpec
	}
	return nil
}

func (x *CallServiceRequest) GetMacaroonHex() string {
	if x != nil {
		return x.MacaroonHex
	}
	return ""
}

func (x *CallServiceRequest) GetPreimageHex() string {
	if x != nil {
		return x.PreimageHex
	}
	return ""
}

type CallServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service-specific output (JSON or binary blob).
	OutputData []byte `protobuf:"bytes,1,opt,name=output_data,json=outputData,proto3" json:"output_data,omitempty"`
	// "success" | "error"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Opaque job identifier for audit / ledger lookup.
	JobId         string `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallServiceResponse) Reset() {
	*x = CallServiceResponse{}
	mi := &file_agent_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallServiceResponse) ProtoMessage() {}

func (x *CallServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallServiceResponse.ProtoReflect.Descriptor instead.
func (*CallServiceResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{1}
}

func (x *CallServiceResponse) GetOutputData() []byte {
	if x != nil {
		return x.OutputData
	}
	return nil
}

func (x *CallServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CallServiceResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// ──────────────────────────────────────────────────────────────────────────────
// L402 challenge — returned in the gRPC error details when payment is required.
// ──────────────────────────────────────────────────────────────────────────────
type PaymentRequired struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BOLT11 invoice the client must pay.
	Invoice string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	// Hex-encoded L402 macaroon to include on the authenticated retry.
	MacaroonHex string `protobuf:"bytes,2,opt,name=macaroon_hex,json=macaroonHex,proto3" json:"macaroon_hex,omitempty"`
	// Hex-encoded SHA256 payment hash.
	PaymentHash string `protobuf:"bytes,3,opt,name=payment_hash,json=paymentHash,proto3" json:"payment_hash,omitempty"`
	// Amount in millisatoshi.
	AmountMsat int64 `protobuf:"varint,4,opt,name=amount_msat,json=amountMsat,proto3" json:"amount_msat,omitempty"`
	// Invoice expiry in seconds.
	ExpirySec     int32 `protobuf:"varint,5,opt,name=expiry_sec,json=expirySec,proto3" json:"expiry_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentRequired) Reset() {
	*x = PaymentRequired{}
	mi := &file_agent_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentRequired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentRequired) ProtoMessage() {}

func (x *PaymentRequired) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentRequired.ProtoReflect.Descriptor instead.
func (*PaymentRequired) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentRequired) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

func (x *PaymentRequired) GetMacaroonHex() string {
	if x != nil {
		return x.MacaroonHex
	}
	return ""
}

func (x *PaymentRequired) GetPaymentHash() string {
	if x != nil {
		return x.PaymentHash
	}
	return ""
}

func (x *PaymentRequired) GetAmountMsat() int64 {
	if x != nil {
		return x.AmountMsat
	}
	return 0
}

func (x *PaymentRequired) GetExpirySec() int32 {
	if x != nil {
		return x.ExpirySec
	}
	return 0
}

type PayHoldInvoiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BOLT11 invoice string to pay.
	Invoice       string `protobuf:"bytes,1,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayHoldInvoiceRequest) Reset() {
	*x = PayHoldInvoiceRequest{}
	mi := &file_agent_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayHoldInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayHoldInvoiceRequest) ProtoMessage() {}

func (x *PayHoldInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayHoldInvoiceRequest.ProtoReflect.Descriptor instead.
func (*PayHoldInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{3}
}

func (x *PayHoldInvoiceRequest) GetInvoice() string {
	if x != nil {
		return x.Invoice
	}
	return ""
}

type PayHoldInvoiceResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// "pending" | "settled" | "failed"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Hex-encoded payment preimage on success.
	Preimage      string `protobuf:"bytes,3,opt,name=preimage,proto3" json:"preimage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayHoldInvoiceResponse) Reset() {
	*x = PayHoldInvoiceResponse{}
	mi := &file_agent_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayHoldInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayHoldInvoiceResponse) ProtoMessage() {}

func (x *PayHoldInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayHoldInvoiceResponse.ProtoReflect.Descriptor instead.
func (*PayHoldInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{4}
}

func (x *PayHoldInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayHoldInvoiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PayHoldInvoiceResponse) GetPreimage() string {
	if x != nil {
		return x.Preimage
	}
	return ""
}

type GetBudgetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetInfoRequest) Reset() {
	*x = GetBudgetInfoRequest{}
	mi := &file_agent_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetInfoRequest) ProtoMessage() {}

func (x *GetBudgetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetInfoRequest) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{5}
}

type GetBudgetInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DailyLimitMsat   int64                  `protobuf:"varint,1,opt,name=daily_limit_msat,json=dailyLimitMsat,proto3" json:"daily_limit_msat,omitempty"`
	DailySpentMsat   int64                  `protobuf:"varint,2,opt,name=daily_spent_msat,json=dailySpentMsat,proto3" json:"daily_spent_msat,omitempty"`
	MonthlyLimitMsat int64                  `protobuf:"varint,3,opt,name=monthly_limit_msat,json=monthlyLimitMsat,proto3" json:"monthly_limit_msat,omitempty"`
	MonthlySpentMsat int64                  `protobuf:"varint,4,opt,name=monthly_spent_msat,json=monthlySpentMsat,proto3" json:"monthly_spent_msat,omitempty"`
	AvailableMsat    int64                  `protobuf:"varint,5,opt,name=available_msat,json=availableMsat,proto3" json:"available_msat,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetBudgetInfoResponse) Reset() {
	*x = GetBudgetInfoResponse{}
	mi := &file_agent_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetInfoResponse) ProtoMessage() {}

func (x *GetBudgetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetInfoResponse) Descriptor() ([]byte, []int) {
	return file_agent_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetBudgetInfoResponse) GetDailyLimitMsat() int64 {
	if x != nil {
		return x.DailyLimitMsat
	}
	return 0
}

func (x *GetBudgetInfoResponse) GetDailySpentMsat() int64 {
	if x != nil {
		return x.DailySpentMsat
	}
	return 0
}

func (x *GetBudgetInfoResponse) GetMonthlyLimitMsat() int64 {
	if x != nil {
		return x.MonthlyLimitMsat
	}
	return 0
}

func (x *GetBudgetInfoResponse) GetMonthlySpentMsat() int64 {
	if x != nil {
		return x.MonthlySpentMsat
	}
	return 0
}

func (x *GetBudgetInfoResponse) GetAvailableMsat() int64 {
	if x != nil {
		return x.AvailableMsat
	}
	return 0
}

var File_agent_service_proto protoreflect.FileDescriptor

const file_agent_service_proto_rawDesc = "" +
	"\n" +
	"\x13agent_service.proto\x12\fkuberbolt.v1\"\x98\x01\n" +
	"\x12CallServiceRequest\x12!\n" +
	"\fservice_kind\x18\x01 \x01(\tR\vserviceKind\x12\x19\n" +
	"\bjob_spec\x18\x02 \x01(\fR\ajobSpec\x12!\n" +
	"\fmacaroon_hex\x18\x03 \x01(\tR\vmacaroonHex\x12!\n" +
	"\fpreimage_hex\x18\x04 \x01(\tR\vpreimageHex\"e\n" +
	"\x13CallServiceResponse\x12\x1f\n" +
	"\voutput_data\x18\x01 \x01(\fR\n" +
	"outputData\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\"\xb1\x01\n" +
	"\x0fPaymentRequired\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\x12!\n" +
	"\fmacaroon_hex\x18\x02 \x01(\tR\vmacaroonHex\x12!\n" +
	"\fpayment_hash\x18\x03 \x01(\tR\vpaymentHash\x12\x1f\n" +
	"\vamount_msat\x18\x04 \x01(\x03R\n" +
	"amountMsat\x12\x1d\n" +
	"\n" +
	"expiry_sec\x18\x05 \x01(\x05R\texpirySec\"1\n" +
	"\x15PayHoldInvoiceRequest\x12\x18\n" +
	"\ainvoice\x18\x01 \x01(\tR\ainvoice\"f\n" +
	"\x16PayHoldInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bpreimage\x18\x03 \x01(\tR\bpreimage\"\x16\n" +
	"\x14GetBudgetInfoRequest\"\xee\x01\n" +
	"\x15GetBudgetInfoResponse\x12(\n" +
	"\x10daily_limit_msat\x18\x01 \x01(\x03R\x0edailyLimitMsat\x12(\n" +
	"\x10daily_spent_msat\x18\x02 \x01(\x03R\x0edailySpentMsat\x12,\n" +
	"\x12monthly_limit_msat\x18\x03 \x01(\x03R\x10monthlyLimitMsat\x12,\n" +
	"\x12monthly_spent_msat\x18\x04 \x01(\x03R\x10monthlySpentMsat\x12%\n" +
	"\x0eavailable_msat\x18\x05 \x01(\x03R\ravailableMsat2\xa0\x02\n" +
	"\x13FinancialPodService\x12R\n" +
	"\vCallService\x12 .kuberbolt.v1.CallServiceRequest\x1a!.kuberbolt.v1.CallServiceResponse\x12[\n" +
	"\x0ePayHoldInvoice\x12#.kuberbolt.v1.PayHoldInvoiceRequest\x1a$.kuberbolt.v1.PayHoldInvoiceResponse\x12X\n" +
	"\rGetBudgetInfo\x12\".kuberbolt.v1.GetBudgetInfoRequest\x1a#.kuberbolt.v1.GetBudgetInfoResponseB3Z1github.com/kuberbolt/financial-pod/internal/pb;pbb\x06proto3"

var (
	file_agent_service_proto_rawDescOnce sync.Once
	file_agent_service_proto_rawDescData []byte
)

func file_agent_service_proto_rawDescGZIP() []byte {
	file_agent_service_proto_rawDescOnce.Do(func() {
		file_agent_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)))
	})
	return file_agent_service_proto_rawDescData
}

var file_agent_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agent_service_proto_goTypes = []any{
	(*CallServiceRequest)(nil),     // 0: kuberbolt.v1.CallServiceRequest
	(*CallServiceResponse)(nil),    // 1: kuberbolt.v1.CallServiceResponse
	(*PaymentRequired)(nil),        // 2: kuberbolt.v1.PaymentRequired
	(*PayHoldInvoiceRequest)(nil),  // 3: kuberbolt.v1.PayHoldInvoiceRequest
	(*PayHoldInvoiceResponse)(nil), // 4: kuberbolt.v1.PayHoldInvoiceResponse
	(*GetBudgetInfoRequest)(nil),   // 5: kuberbolt.v1.GetBudgetInfoRequest
	(*GetBudgetInfoResponse)(nil),  // 6: kuberbolt.v1.GetBudgetInfoResponse
}
var file_agent_service_proto_depIdxs = []int32{
	0, // 0: kuberbolt.v1.FinancialPodService.CallService:input_type -> kuberbolt.v1.CallServiceRequest
	3, // 1: kuberbolt.v1.FinancialPodService.PayHoldInvoice:input_type -> kuberbolt.v1.PayHoldInvoiceRequest
	5, // 2: kuberbolt.v1.FinancialPodService.GetBudgetInfo:input_type -> kuberbolt.v1.GetBudgetInfoRequest
	1, // 3: kuberbolt.v1.FinancialPodService.CallService:output_type -> kuberbolt.v1.CallServiceResponse
	4, // 4: kuberbolt.v1.FinancialPodService.PayHoldInvoice:output_type -> kuberbolt.v1.PayHoldInvoiceResponse
	6, // 5: kuberbolt.v1.FinancialPodService.GetBudgetInfo:output_type -> kuberbolt.v1.GetBudgetInfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_service_proto_init() }
func file_agent_service_proto_init() {
	if File_agent_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_service_proto_rawDesc), len(file_agent_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_service_proto_goTypes,
		DependencyIndexes: file_agent_service_proto_depIdxs,
		MessageInfos:      file_agent_service_proto_msgTypes,
	}.Build()
	File_agent_service_proto = out.File
	file_agent_service_proto_goTypes = nil
	file_agent_service_proto_depIdxs = nil
}
